" use bash as default shell
set shell=bash

" don't bother with vi compatibility
set nocompatible

" enable syntax highlighting
syntax enable

" configure Vundle
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'airblade/vim-gitgutter'                 " shows a git diff in the 'gutter'
Plugin 'mustache/vim-mustache-handlebars'
Plugin 'kchmck/vim-coffee-script'
Plugin 'kien/ctrlp.vim'                         " https://github.com/kien/ctrlp.vim
Plugin 'rking/ag.vim'
Plugin 'nathanaelkane/vim-indent-guides'        " Indent Guides is a plugin for visually displaying indent
Plugin 'pangloss/vim-javascript'
Plugin 'wookiehangover/jshint.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'                   " Syntastic is a syntax checking plugin
Plugin 'tpope/vim-commentary'                   " Comment stuff out
Plugin 'tpope/vim-endwise'                      " wisely add 'end' in ruby
Plugin 'tpope/vim-fugitive'                     " a Git wrapper so awesome, it should be illegal
Plugin 'tpope/vim-repeat'                       " enable repeating supported plugin maps with '.'
Plugin 'tpope/vim-surround'                     " is all about 'surroundings': parentheses, brackets, quotes, XML tags, and more
Plugin 'tpope/vim-unimpaired'                   " pairs of handy bracket mappings
Plugin 'vim-scripts/Align'                      " Help folks to align text, eqns, declarations, tables
Plugin 'vim-scripts/greplace.vim'               " allow you to search and replace a pattern across multiple files
Plugin 'vim-scripts/matchit.zip'                " allow you to configure % to match more than just single characters
Plugin 'terryma/vim-multiple-cursors'           " True Sublime Text style multiple selections for Vim
Plugin 'bling/vim-airline'                      " Fancy status bar
Plugin 'ap/vim-css-color'                       " highlight colors in css files
Plugin 'wting/rust.vim'
Plugin 'wavded/vim-stylus'                      " Stylus css preprocessor
Plugin 'ervandew/supertab'                      " Add Tab autocompletation

" Theme
Plugin 'altercation/vim-colors-solarized'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line ensure ftdetect et al work by including this after the Vundle stuff

" Theme
set background=dark
" solarized options
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
let g:solarized_termcolors=256
colorscheme solarized

" general settings
set autoindent
set autoread                                                 " reload files when changed on disk, i.e. via `git checkout`
set backspace=2                                              " Fix broken backspace in some setups
set backupcopy=yes                                           " see :help crontab
set clipboard=unnamed                                        " yank and paste with the system clipboard
set directory-=.                                             " don't store swapfiles in the current directory
set encoding=utf-8
set expandtab                                                " expand tabs to spaces
set ignorecase                                               " case-insensitive search
set incsearch                                                " search as you type
set hlsearch                                                 " highlight search
set cursorline                                               " don't highlight current line
set laststatus=2                                             " always show statusline
set list                                                     " show trailing whitespace
set listchars=tab:▸\ ,eol:¬,nbsp:⋅,trail:•
set number                                                   " show line numbers
set ruler                                                    " show where you are
set scrolloff=3                                              " show context above/below cursorline
set shiftwidth=2                                             " normal mode indentation commands use 2 spaces
set showcmd                                                  " the bottom line in your editor will show you information about the current command going on
set smartcase                                                " case-sensitive search if any caps
set softtabstop=2                                            " insert mode tab and backspace use 2 spaces
set tabstop=8                                                " actual tabs occupy 8 characters
set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc
set wildmenu                                                 " show a navigable menu for tab completion
set wildmode=longest,list,full
set guioptions-=Be
set guioptions=aAc
set columns=999
set lines=999

" Enable basic mouse behavior such as resizing buffers.
set mouse=a

" keyboard shortcuts
let mapleader = '\'
nnoremap <leader>gb :Gblame<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gc :Gcommit<CR>
nnoremap <leader>cc :CoffeeCompile<CR>
nnoremap <leader>l :Align
noremap <C-F> :Ag<space>
nnoremap <leader>b :CtrlPBuffer<CR>
nnoremap <leader>n :NERDTreeToggle<CR>
nnoremap <leader>f :NERDTreeFind<CR>
nnoremap <leader>t :CtrlP<CR>
nnoremap <leader>T :CtrlPClearCache<CR>:CtrlP<CR>
nnoremap <leader>] :TagbarToggle<CR>
nnoremap <leader>g :GitGutterToggle<CR>

" Don't copy the contents of an overwritten selection.
vnoremap p "_dP
" plugin settings

let g:ctrlp_match_window = 'order:ttb,max:20'
let g:NERDSpaceDelims=1

" Use The Silver Searcher https://github.com/ggreer/the_silver_searcher
if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif

" Trim white spaces
function! TrimWhiteSpace()
    %s/\s\+$//e
endfunction

autocmd BufWritePre * :call TrimWhiteSpace()

" fdoc is yaml
autocmd BufRead,BufNewFile *.fdoc set filetype=yaml
" md is markdown
autocmd BufRead,BufNewFile *.md set filetype=markdown
autocmd BufRead,BufNewFile *.* set spell

" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =
